var searchData=
[
  ['cache_20info_20config_0',['Fields Description for Cache Info Config',['../index.html#autotoc_md46',1,'']]],
  ['cacheinfo_1',['CacheInfo',['../structCacheInfo.html',1,'']]],
  ['callbacks_2',['2. Applier and Teardown Callbacks',['../extensions_usage.html#autotoc_md126',1,'']]],
  ['capabilities_3',['2. Defining feature init, relay and teardown capabilities',['../ext_features.html#autotoc_md131',1,'']]],
  ['capacity_20for_20efficiency_4',['11. Pre-Allocate Capacity for efficiency',['../index.html#autotoc_md107',1,'']]],
  ['cgroup_20config_5',['cgroup config',['../index.html#autotoc_md44',1,'Fields Description for CGroup Config'],['../usage.html#autotoc_md142',1,'Sample Cgroup config']]],
  ['cgroupconfiginfo_6',['CGroupConfigInfo',['../structCGroupConfigInfo.html',1,'']]],
  ['cgroups_20map_7',['cgroups map',['../index.html#autotoc_md42',1,'2. Cgroups map'],['../index.html#autotoc_md17',1,'2. Cgroups map']]],
  ['checking_8',['6. Duplicate Checking',['../index.html#autotoc_md102',1,'']]],
  ['classifier_9',['Contextual Classifier',['../index.html#autotoc_md12',1,'']]],
  ['cleanup_10',['4. Pulse Monitor: Detection of Dead Clients and Subsequent Cleanup',['../index.html#autotoc_md100',1,'']]],
  ['cli_11',['cli',['../client_cli.html#autotoc_md118',1,'Client CLI'],['../index.html#autotoc_md109',1,'Client CLI'],['../client_cli.html',1,'Interacting via Client CLI']]],
  ['client_20apis_12',['Client APIs',['../group__RESOURCE__TUNER__CLIENT__APIS.html',1,'']]],
  ['client_20cli_13',['client cli',['../index.html#autotoc_md109',1,'Client CLI'],['../client_cli.html#autotoc_md118',1,'Client CLI'],['../client_cli.html',1,'Interacting via Client CLI']]],
  ['client_20garbage_20collector_14',['Client Garbage Collector',['../group__CLIENT__GARBAGE__COLLECTOR.html',1,'']]],
  ['client_20level_20permissions_15',['1. Client-Level Permissions',['../index.html#autotoc_md97',1,'']]],
  ['clientdatamanager_16',['ClientDataManager',['../classClientDataManager.html',1,'']]],
  ['clientexists_17',['clientExists',['../classClientDataManager.html#abdaa9fb64a8ff9cbebfbeeb34bab2ac4',1,'ClientDataManager']]],
  ['clientgarbagecollector_18',['ClientGarbageCollector',['../classClientGarbageCollector.html',1,'']]],
  ['clientgarbagecollector_2eh_19',['ClientGarbageCollector.h',['../ClientGarbageCollector_8h.html',1,'']]],
  ['clients_20and_20subsequent_20cleanup_20',['4. Pulse Monitor: Detection of Dead Clients and Subsequent Cleanup',['../index.html#autotoc_md100',1,'']]],
  ['cluster_20map_21',['cluster map',['../index.html#autotoc_md16',1,'1. Logical Cluster Map'],['../index.html#autotoc_md41',1,'1. Logical Cluster Map']]],
  ['clusterinfo_22',['ClusterInfo',['../structClusterInfo.html',1,'']]],
  ['cocotable_23',['cocotable',['../classCocoTable.html',1,'CocoTable'],['../group__COCO__TABLE.html',1,'Concurrency Coordinator Table (CocoTable)']]],
  ['cocotable_2eh_24',['CocoTable.h',['../CocoTable_8h.html',1,'']]],
  ['collector_25',['Client Garbage Collector',['../group__CLIENT__GARBAGE__COLLECTOR.html',1,'']]],
  ['common_20initialization_20configs_26',['Common Initialization Configs',['../index.html#autotoc_md38',1,'']]],
  ['common_20properties_20configs_27',['Common Properties Configs',['../index.html#autotoc_md57',1,'']]],
  ['common_20resource_20configs_28',['Common Resource Configs',['../index.html#autotoc_md50',1,'']]],
  ['componentregistry_29',['ComponentRegistry',['../classComponentRegistry.html',1,'']]],
  ['concurrency_20coordinator_20table_20cocotable_30',['Concurrency Coordinator Table (CocoTable)',['../group__COCO__TABLE.html',1,'']]],
  ['config_31',['config',['../index.html#autotoc_md56',1,'3. Properties Config'],['../index.html#autotoc_md46',1,'Fields Description for Cache Info Config'],['../index.html#autotoc_md44',1,'Fields Description for CGroup Config'],['../index.html#autotoc_md45',1,'Fields Description for Mpam Group Config'],['../usage.html#autotoc_md142',1,'Sample Cgroup config']]],
  ['config_20file_32',['config file',['../usage.html#autotoc_md145',1,'Sample Device Config file'],['../usage.html#autotoc_md148',1,'Sample Properties config file.']]],
  ['config_20file_20with_20two_20resources_33',['Sample Resource config file with two resources.',['../usage.html#autotoc_md136',1,'']]],
  ['config_20files_20format_34',['Config Files Format',['../index.html#autotoc_md36',1,'']]],
  ['configs_35',['configs',['../index.html#autotoc_md37',1,'1. Initialization Configs'],['../index.html#autotoc_md49',1,'2. Resource Configs'],['../extensions_usage.html#autotoc_md127',1,'3. Custom Configs'],['../usage.html#autotoc_md141',1,'3. How to add init configs'],['../index.html#autotoc_md62',1,'4. Signal Configs'],['../index.html#autotoc_md65',1,'5. (Optional) Target Configs'],['../index.html#autotoc_md68',1,'6. (Optional) ExtFeatures Configs'],['../index.html#autotoc_md38',1,'Common Initialization Configs'],['../index.html#autotoc_md57',1,'Common Properties Configs'],['../index.html#autotoc_md50',1,'Common Resource Configs'],['../index.html#autotoc_md39',1,'Overriding Initialization Configs'],['../index.html#autotoc_md58',1,'Overriding Properties Configs'],['../index.html#autotoc_md51',1,'Overriding Resource Configs']]],
  ['contact_36',['Contact',['../index.html#autotoc_md116',1,'']]],
  ['contents_37',['Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['contextual_20classifier_38',['Contextual Classifier',['../index.html#autotoc_md12',1,'']]],
  ['coordinator_20table_20cocotable_39',['Concurrency Coordinator Table (CocoTable)',['../group__COCO__TABLE.html',1,'']]],
  ['cpu_20architecture_20details_40',['4. How to enforce CPU architecture details',['../usage.html#autotoc_md144',1,'']]],
  ['crash_20recovery_41',['9. Crash Recovery',['../index.html#autotoc_md105',1,'']]],
  ['create_20a_20resource_20opcode_20rescode_20and_20signal_20opcode_20sigcode_42',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md149',1,'']]],
  ['createnewclient_43',['createNewClient',['../classClientDataManager.html#a9dadece9ae9515cea2ae5a7fc20bd063',1,'ClientDataManager']]],
  ['createproperty_44',['createProperty',['../classPropertiesRegistry.html#ae0a22440795ed868651da51f8af43f85',1,'PropertiesRegistry']]],
  ['custom_20configs_45',['3. Custom Configs',['../extensions_usage.html#autotoc_md127',1,'']]],
  ['custom_20extension_20file_46',['custom extension file',['../index.html#autotoc_md40',1,'Overiding with Custom Extension File'],['../index.html#autotoc_md52',1,'Overiding with Custom Extension File']]],
  ['custom_20properties_20file_47',['Overiding with Custom Properties File',['../index.html#autotoc_md59',1,'']]],
  ['custom_20resource_48',['1. How to add a custom resource',['../usage.html#autotoc_md135',1,'']]]
];
