var searchData=
[
  ['cacheinfo_0',['CacheInfo',['../structCacheInfo.html',1,'']]],
  ['callbacks_1',['callbacks',['../extensions_usage.html#autotoc_md81',1,'2. Applier and Teardown Callbacks'],['../index.html#autotoc_md44',1,'6.1.1. Registering Resource Callbacks']]],
  ['capabilities_2',['2. Defining feature init, relay and teardown capabilities',['../ext_features.html#autotoc_md86',1,'']]],
  ['capacity_20for_20efficiency_3',['7.13. Pre-Allocate Capacity for efficiency',['../index.html#autotoc_md70',1,'']]],
  ['cgroup_20config_4',['Sample Cgroup config',['../usage.html#autotoc_md97',1,'']]],
  ['cgroupconfiginfo_5',['CGroupConfigInfo',['../structCGroupConfigInfo.html',1,'']]],
  ['checking_6',['7.8. Duplicate Checking',['../index.html#autotoc_md65',1,'']]],
  ['classifier_7',['7.2.1. Contextual Classifier',['../index.html#autotoc_md56',1,'']]],
  ['cleanup_8',['7.6. Pulse Monitor: Detection of Dead Clients and Subsequent Cleanup',['../index.html#autotoc_md63',1,'']]],
  ['cli_9',['cli',['../index.html#autotoc_md36',1,'5. Client CLI'],['../client_cli.html#autotoc_md73',1,'Client CLI'],['../client_cli.html',1,'Interacting via Client CLI']]],
  ['client_20apis_10',['Client APIs',['../group__RESOURCE__TUNER__CLIENT__APIS.html',1,'']]],
  ['client_20cli_11',['client cli',['../index.html#autotoc_md36',1,'5. Client CLI'],['../client_cli.html#autotoc_md73',1,'Client CLI'],['../client_cli.html',1,'Interacting via Client CLI']]],
  ['client_20garbage_20collector_12',['Client Garbage Collector',['../group__CLIENT__GARBAGE__COLLECTOR.html',1,'']]],
  ['client_20level_20permissions_13',['7.3. Client-Level Permissions',['../index.html#autotoc_md60',1,'']]],
  ['clientdatamanager_14',['ClientDataManager',['../classClientDataManager.html',1,'']]],
  ['clientexists_15',['clientExists',['../classClientDataManager.html#abdaa9fb64a8ff9cbebfbeeb34bab2ac4',1,'ClientDataManager']]],
  ['clientgarbagecollector_16',['ClientGarbageCollector',['../classClientGarbageCollector.html',1,'']]],
  ['clientgarbagecollector_2eh_17',['ClientGarbageCollector.h',['../ClientGarbageCollector_8h.html',1,'']]],
  ['clients_20and_20subsequent_20cleanup_18',['7.6. Pulse Monitor: Detection of Dead Clients and Subsequent Cleanup',['../index.html#autotoc_md63',1,'']]],
  ['clusterinfo_19',['ClusterInfo',['../structClusterInfo.html',1,'']]],
  ['cocotable_20',['cocotable',['../classCocoTable.html',1,'CocoTable'],['../group__COCO__TABLE.html',1,'Concurrency Coordinator Table (CocoTable)']]],
  ['cocotable_2eh_21',['CocoTable.h',['../CocoTable_8h.html',1,'']]],
  ['code_20construction_22',['4.2.4.1. Signal Code Construction',['../index.html#autotoc_md24',1,'']]],
  ['collector_23',['Client Garbage Collector',['../group__CLIENT__GARBAGE__COLLECTOR.html',1,'']]],
  ['componentregistry_24',['ComponentRegistry',['../classComponentRegistry.html',1,'']]],
  ['concurrency_20coordinator_20table_20cocotable_25',['Concurrency Coordinator Table (CocoTable)',['../group__COCO__TABLE.html',1,'']]],
  ['config_26',['config',['../index.html#autotoc_md33',1,'4.3.3. Properties Config'],['../index.html#autotoc_md49',1,'6.2.3. Properties Config'],['../usage.html#autotoc_md97',1,'Sample Cgroup config']]],
  ['config_20file_27',['config file',['../usage.html#autotoc_md100',1,'Sample Device Config file'],['../usage.html#autotoc_md103',1,'Sample Properties config file.']]],
  ['config_20file_20with_20two_20resources_28',['Sample Resource config file with two resources.',['../usage.html#autotoc_md91',1,'']]],
  ['configs_29',['configs',['../extensions_usage.html#autotoc_md82',1,'3. Custom Configs'],['../usage.html#autotoc_md96',1,'3. How to add init configs'],['../index.html#autotoc_md30',1,'4.3. Configs'],['../index.html#autotoc_md31',1,'4.3.1. Initialization Configs'],['../index.html#autotoc_md32',1,'4.3.2. Resource Configs'],['../index.html#autotoc_md34',1,'4.3.4. Signal Configs'],['../index.html#autotoc_md35',1,'4.3.5. Per App Configs'],['../index.html#autotoc_md45',1,'6.1.2. Registering Custom Configs'],['../index.html#autotoc_md46',1,'6.2. Custom Configs'],['../index.html#autotoc_md47',1,'6.2.1. Initialization Configs'],['../index.html#autotoc_md48',1,'6.2.2. Resource Configs'],['../index.html#autotoc_md50',1,'6.2.4. Signal Configs'],['../index.html#autotoc_md51',1,'6.2.5. Target Configs']]],
  ['configurable_20resources_20and_20signals_30',['3. Configurable Resources and Signals',['../index.html#autotoc_md8',1,'']]],
  ['construction_31',['construction',['../index.html#autotoc_md16',1,'4.2.1.2. Resource ResCode Construction'],['../index.html#autotoc_md17',1,'4.2.1.3. Resource ResInfo Construction'],['../index.html#autotoc_md24',1,'4.2.4.1. Signal Code Construction']]],
  ['contact_32',['8. Contact',['../index.html#autotoc_md71',1,'']]],
  ['contents_33',['Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['contextual_20classifier_34',['7.2.1. Contextual Classifier',['../index.html#autotoc_md56',1,'']]],
  ['control_35',['1.2. Powerful System‑Level Control',['../index.html#autotoc_md4',1,'']]],
  ['coordinator_20table_20cocotable_36',['Concurrency Coordinator Table (CocoTable)',['../group__COCO__TABLE.html',1,'']]],
  ['cpu_20architecture_20details_37',['4. How to enforce CPU architecture details',['../usage.html#autotoc_md99',1,'']]],
  ['crash_20recovery_38',['7.11. Crash Recovery',['../index.html#autotoc_md68',1,'']]],
  ['create_20a_20resource_20opcode_20rescode_20and_20signal_20opcode_20sigcode_39',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md104',1,'']]],
  ['createnewclient_40',['createNewClient',['../classClientDataManager.html#a9dadece9ae9515cea2ae5a7fc20bd063',1,'ClientDataManager']]],
  ['createproperty_41',['createProperty',['../classPropertiesRegistry.html#ae0a22440795ed868651da51f8af43f85',1,'PropertiesRegistry']]],
  ['custom_20configs_42',['custom configs',['../extensions_usage.html#autotoc_md82',1,'3. Custom Configs'],['../index.html#autotoc_md45',1,'6.1.2. Registering Custom Configs'],['../index.html#autotoc_md46',1,'6.2. Custom Configs']]],
  ['custom_20resource_43',['1. How to add a custom resource',['../usage.html#autotoc_md90',1,'']]],
  ['customizations_20extensions_44',['6. Customizations &amp; Extensions',['../index.html#autotoc_md42',1,'']]]
];
