var searchData=
[
  ['table_20cocotable_0',['Concurrency Coordinator Table (CocoTable)',['../group__COCO__TABLE.html',1,'']]],
  ['table_20of_20contents_1',['Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['table_20to_20get_20the_20value_20of_20restype_20for_20a_20resource_2',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md74',1,'']]],
  ['target_20configs_3',['5. (Optional) Target Configs',['../index.html#autotoc_md65',1,'']]],
  ['targetregistry_4',['TargetRegistry',['../classTargetRegistry.html',1,'']]],
  ['targetregistry_2eh_5',['TargetRegistry.h',['../TargetRegistry_8h.html',1,'']]],
  ['teardown_20callbacks_6',['2. Applier and Teardown Callbacks',['../extensions_usage.html#autotoc_md126',1,'']]],
  ['teardown_20capabilities_7',['2. Defining feature init, relay and teardown capabilities',['../ext_features.html#autotoc_md131',1,'']]],
  ['teardownfeatures_8',['teardownFeatures',['../classExtFeaturesRegistry.html#aa563b40b2c05933b18e64f4597ae251a',1,'ExtFeaturesRegistry']]],
  ['the_20extfeaturesconfig_20yaml_20be_20placed_9',['3. Where should the ExtFeaturesConfig.yaml be placed?',['../ext_features.html#autotoc_md133',1,'']]],
  ['the_20resource_20tune_20and_20untune_20functionalities_10',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md139',1,'']]],
  ['the_20value_20of_20restype_20for_20a_20resource_11',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md74',1,'']]],
  ['this_20table_20to_20get_20the_20value_20of_20restype_20for_20a_20resource_12',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md74',1,'']]],
  ['to_20add_20a_20custom_20resource_13',['1. How to add a custom resource',['../usage.html#autotoc_md135',1,'']]],
  ['to_20add_20a_20new_20property_14',['5. How to add a new Property',['../usage.html#autotoc_md147',1,'']]],
  ['to_20add_20init_20configs_15',['3. How to add init configs',['../usage.html#autotoc_md141',1,'']]],
  ['to_20create_20a_20resource_20opcode_20rescode_20and_20signal_20opcode_20sigcode_16',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md149',1,'']]],
  ['to_20enforce_20cpu_20architecture_20details_17',['4. How to enforce CPU architecture details',['../usage.html#autotoc_md144',1,'']]],
  ['to_20get_20the_20value_20of_20restype_20for_20a_20resource_18',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md74',1,'']]],
  ['to_20override_20the_20resource_20tune_20and_20untune_20functionalities_19',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md139',1,'']]],
  ['to_20physical_20mapping_20',['7. Dynamic Mapper: Logical to Physical Mapping',['../index.html#autotoc_md103',1,'']]],
  ['tune_20and_20untune_20functionalities_21',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md139',1,'']]],
  ['tune_20request_22',['tune request',['../index.html#autotoc_md111',1,'1. Send a Tune Request'],['../client_cli.html#autotoc_md120',1,'1. Send a Tune Request']]],
  ['tune_20requests_20formulation_20guide_23',['&quot;Tune&quot; Requests Formulation Guide',['../requests_formulation.html',1,'']]],
  ['tuner_24',['Resource Tuner',['../index.html#autotoc_md11',1,'']]],
  ['tuner_20apis_25',['Example Usage of Resource Tuner APIs',['../index.html#autotoc_md76',1,'']]],
  ['tuner_20features_26',['Resource Tuner Features',['../index.html#autotoc_md93',1,'']]],
  ['tuneresources_27',['tuneresources',['../group__RESOURCE__TUNER__CLIENT__APIS.html#ga1eac546e5691c0c3d5d7036a68ba6a2b',1,'tuneResources():&#160;UrmAPIs.h'],['../index.html#autotoc_md22',1,'tuneResources'],['../index.html#autotoc_md77',1,'tuneResources']]],
  ['tunesignal_28',['tunesignal',['../index.html#autotoc_md28',1,'tuneSignal'],['../group__RESOURCE__TUNER__CLIENT__APIS.html#ga3c652f0874217ba2df98289c8c556311',1,'tuneSignal():&#160;UrmAPIs.h']]],
  ['tunesignal_20request_29',['tunesignal request',['../client_cli.html#autotoc_md124',1,'5. Send a tuneSignal Request'],['../index.html#autotoc_md115',1,'5. Send a tuneSignal Request']]],
  ['tuning_20framework_30',['Userspace Resource Manager: A System Resource Tuning Framework',['../index.html',1,'']]],
  ['two_20resources_31',['Sample Resource config file with two resources.',['../usage.html#autotoc_md136',1,'']]],
  ['types_20use_20this_20table_20to_20get_20the_20value_20of_20restype_20for_20a_20resource_32',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md74',1,'']]]
];
