var searchData=
[
  ['sample_20cgroup_20config_0',['Sample Cgroup config',['../usage.html#autotoc_md97',1,'']]],
  ['sample_20device_20config_20file_1',['Sample Device Config file',['../usage.html#autotoc_md100',1,'']]],
  ['sample_20properties_20config_20file_2',['Sample Properties config file.',['../usage.html#autotoc_md103',1,'']]],
  ['sample_20resource_20config_20file_20with_20two_20resources_3',['Sample Resource config file with two resources.',['../usage.html#autotoc_md91',1,'']]],
  ['send_20a_20getprop_20request_4',['send a getprop request',['../client_cli.html#autotoc_md78',1,'4. Send a getProp Request'],['../index.html#autotoc_md40',1,'5.4. Send a getProp Request']]],
  ['send_20a_20retune_20request_5',['send a retune request',['../client_cli.html#autotoc_md77',1,'3. Send a Retune Request'],['../index.html#autotoc_md39',1,'5.3. Send a Retune Request']]],
  ['send_20a_20tune_20request_6',['send a tune request',['../client_cli.html#autotoc_md75',1,'1. Send a Tune Request'],['../index.html#autotoc_md37',1,'5.1. Send a Tune Request']]],
  ['send_20a_20tunesignal_20request_7',['send a tunesignal request',['../client_cli.html#autotoc_md79',1,'5. Send a tuneSignal Request'],['../index.html#autotoc_md41',1,'5.5. Send a tuneSignal Request']]],
  ['send_20an_20untune_20request_8',['send an untune request',['../client_cli.html#autotoc_md76',1,'2. Send an Untune Request'],['../index.html#autotoc_md38',1,'5.2. Send an Untune Request']]],
  ['should_20the_20extfeaturesconfig_20yaml_20be_20placed_9',['3. Where should the ExtFeaturesConfig.yaml be placed?',['../ext_features.html#autotoc_md88',1,'']]],
  ['shouldrequestbeadded_10',['shouldRequestBeAdded',['../classRequestManager.html#af467481df904900af4035c7c4e993603',1,'RequestManager']]],
  ['sigcode_11',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md104',1,'']]],
  ['signal_12',['Signal',['../classSignal.html',1,'']]],
  ['signal_20code_20construction_13',['4.2.4.1. Signal Code Construction',['../index.html#autotoc_md24',1,'']]],
  ['signal_20configs_14',['signal configs',['../index.html#autotoc_md34',1,'4.3.4. Signal Configs'],['../index.html#autotoc_md50',1,'6.2.4. Signal Configs']]],
  ['signal_20opcode_20sigcode_15',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md104',1,'']]],
  ['signalinfo_16',['SignalInfo',['../structSignalInfo.html',1,'']]],
  ['signalinternal_2eh_17',['SignalInternal.h',['../SignalInternal_8h.html',1,'']]],
  ['signalregistry_18',['SignalRegistry',['../classSignalRegistry.html',1,'']]],
  ['signals_19',['signals',['../index.html#autotoc_md5',1,'1.3. Dynamic Resource Provisioning via Signals'],['../index.html#autotoc_md8',1,'3. Configurable Resources and Signals'],['../index.html#autotoc_md10',1,'3.2. Signals']]],
  ['signals_20and_20features_20',['1. Making Use of Relay Signals and Features',['../ext_features.html#autotoc_md84',1,'']]],
  ['startclientgarbagecollectordaemon_21',['startClientGarbageCollectorDaemon',['../classClientGarbageCollector.html#a6012f1e50f06f70d1640944ce6314fd8',1,'ClientGarbageCollector']]],
  ['started_22',['2. Getting Started',['../index.html#autotoc_md7',1,'']]],
  ['startpulsemonitordaemon_23',['startPulseMonitorDaemon',['../classPulseMonitor.html#a8932d2321e409e049b8f55cfe3b9c120',1,'PulseMonitor']]],
  ['structure_24',['7.1. Project Structure',['../index.html#autotoc_md54',1,'']]],
  ['submitpropgetrequest_25',['submitPropGetRequest',['../RestuneInternal_8h.html#a68a464515fbd0a22a3b80b1c3b707553',1,'RestuneInternal.h']]],
  ['submitproprequest_26',['submitPropRequest',['../RestuneInternal_8h.html#a4c0fb3f059edc4952080e3cea6a66bcf',1,'RestuneInternal.h']]],
  ['submitpropsetrequest_27',['submitPropSetRequest',['../RestuneInternal_8h.html#acd9cb104aea5b0f501a8a9a78aa6dd4b',1,'RestuneInternal.h']]],
  ['submitresprovisionreqmsg_28',['submitResProvisionReqMsg',['../RestuneInternal_8h.html#a0b4e3e16698adef003b71aa9546718e5',1,'RestuneInternal.h']]],
  ['submitsignalrequest_29',['submitSignalRequest',['../SignalInternal_8h.html#a8afb0e0e0e8c22624fac55d0a7ea0d83',1,'SignalInternal.h']]],
  ['subsequent_20cleanup_30',['7.6. Pulse Monitor: Detection of Dead Clients and Subsequent Cleanup',['../index.html#autotoc_md63',1,'']]],
  ['sysresource_31',['sysresource',['../index.html#autotoc_md15',1,'4.2.1.1. SysResource'],['../structSysResource.html',1,'SysResource']]],
  ['system‑level_20control_32',['1.2. Powerful System‑Level Control',['../index.html#autotoc_md4',1,'']]],
  ['system_20abuse_33',['7.7. Rate Limiter: Preventing System Abuse',['../index.html#autotoc_md64',1,'']]],
  ['system_20resource_20tuning_20framework_34',['Userspace Resource Manager: A System Resource Tuning Framework',['../index.html',1,'']]]
];
