var searchData=
[
  ['table_20cocotable_0',['Concurrency Coordinator Table (CocoTable)',['../group__COCO__TABLE.html',1,'']]],
  ['table_20of_20contents_1',['Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['target_20configs_2',['6.2.5. Target Configs',['../index.html#autotoc_md51',1,'']]],
  ['targetregistry_3',['TargetRegistry',['../classTargetRegistry.html',1,'']]],
  ['targetregistry_2eh_4',['TargetRegistry.h',['../TargetRegistry_8h.html',1,'']]],
  ['teardown_20callbacks_5',['2. Applier and Teardown Callbacks',['../extensions_usage.html#autotoc_md81',1,'']]],
  ['teardown_20capabilities_6',['2. Defining feature init, relay and teardown capabilities',['../ext_features.html#autotoc_md86',1,'']]],
  ['teardownfeatures_7',['teardownFeatures',['../classExtFeaturesRegistry.html#aa563b40b2c05933b18e64f4597ae251a',1,'ExtFeaturesRegistry']]],
  ['the_20extfeaturesconfig_20yaml_20be_20placed_8',['3. Where should the ExtFeaturesConfig.yaml be placed?',['../ext_features.html#autotoc_md88',1,'']]],
  ['the_20resource_20tune_20and_20untune_20functionalities_9',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md94',1,'']]],
  ['to_20add_20a_20custom_20resource_10',['1. How to add a custom resource',['../usage.html#autotoc_md90',1,'']]],
  ['to_20add_20a_20new_20property_11',['5. How to add a new Property',['../usage.html#autotoc_md102',1,'']]],
  ['to_20add_20init_20configs_12',['3. How to add init configs',['../usage.html#autotoc_md96',1,'']]],
  ['to_20create_20a_20resource_20opcode_20rescode_20and_20signal_20opcode_20sigcode_13',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md104',1,'']]],
  ['to_20enforce_20cpu_20architecture_20details_14',['4. How to enforce CPU architecture details',['../usage.html#autotoc_md99',1,'']]],
  ['to_20override_20the_20resource_20tune_20and_20untune_20functionalities_15',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md94',1,'']]],
  ['to_20physical_20mapping_16',['7.9. Dynamic Mapper: Logical to Physical Mapping',['../index.html#autotoc_md66',1,'']]],
  ['tune_20and_20untune_20functionalities_17',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md94',1,'']]],
  ['tune_20request_18',['tune request',['../client_cli.html#autotoc_md75',1,'1. Send a Tune Request'],['../index.html#autotoc_md37',1,'5.1. Send a Tune Request']]],
  ['tune_20requests_20formulation_20guide_19',['&quot;Tune&quot; Requests Formulation Guide',['../requests_formulation.html',1,'']]],
  ['tuner_20',['7.2.2. Resource Tuner',['../index.html#autotoc_md57',1,'']]],
  ['tuneresources_21',['tuneresources',['../index.html#autotoc_md14',1,'4.2.1. tuneResources'],['../group__RESOURCE__TUNER__CLIENT__APIS.html#ga1eac546e5691c0c3d5d7036a68ba6a2b',1,'tuneResources():&#160;UrmAPIs.h']]],
  ['tunesignal_22',['tunesignal',['../index.html#autotoc_md23',1,'4.2.4. tuneSignal'],['../group__RESOURCE__TUNER__CLIENT__APIS.html#ga3c652f0874217ba2df98289c8c556311',1,'tuneSignal():&#160;UrmAPIs.h']]],
  ['tunesignal_20request_23',['tunesignal request',['../client_cli.html#autotoc_md79',1,'5. Send a tuneSignal Request'],['../index.html#autotoc_md41',1,'5.5. Send a tuneSignal Request']]],
  ['tuning_20framework_24',['Userspace Resource Manager: A System Resource Tuning Framework',['../index.html',1,'']]],
  ['two_20resources_25',['Sample Resource config file with two resources.',['../usage.html#autotoc_md91',1,'']]]
];
