var searchData=
[
  ['a_20custom_20resource_0',['1. How to add a custom resource',['../usage.html#autotoc_md135',1,'']]],
  ['a_20getprop_20request_1',['a getprop request',['../index.html#autotoc_md114',1,'4. Send a getProp Request'],['../client_cli.html#autotoc_md123',1,'4. Send a getProp Request']]],
  ['a_20new_20property_2',['5. How to add a new Property',['../usage.html#autotoc_md147',1,'']]],
  ['a_20resource_3',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md74',1,'']]],
  ['a_20resource_20opcode_20rescode_20and_20signal_20opcode_20sigcode_4',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md149',1,'']]],
  ['a_20retune_20request_5',['a retune request',['../client_cli.html#autotoc_md122',1,'3. Send a Retune Request'],['../index.html#autotoc_md113',1,'3. Send a Retune Request']]],
  ['a_20system_20resource_20tuning_20framework_6',['Userspace Resource Manager: A System Resource Tuning Framework',['../index.html',1,'']]],
  ['a_20tune_20request_7',['a tune request',['../index.html#autotoc_md111',1,'1. Send a Tune Request'],['../client_cli.html#autotoc_md120',1,'1. Send a Tune Request']]],
  ['a_20tunesignal_20request_8',['a tunesignal request',['../client_cli.html#autotoc_md124',1,'5. Send a tuneSignal Request'],['../index.html#autotoc_md115',1,'5. Send a tuneSignal Request']]],
  ['abuse_9',['5. Rate Limiter: Preventing System Abuse',['../index.html#autotoc_md101',1,'']]],
  ['add_20a_20custom_20resource_10',['1. How to add a custom resource',['../usage.html#autotoc_md135',1,'']]],
  ['add_20a_20new_20property_11',['5. How to add a new Property',['../usage.html#autotoc_md147',1,'']]],
  ['add_20init_20configs_12',['3. How to add init configs',['../usage.html#autotoc_md141',1,'']]],
  ['addrequest_13',['addRequest',['../classRequestManager.html#aa819a5b2d3c9be0a29b9075b276b9518',1,'RequestManager']]],
  ['allocate_20capacity_20for_20efficiency_14',['11. Pre-Allocate Capacity for efficiency',['../index.html#autotoc_md107',1,'']]],
  ['an_20untune_20request_15',['an untune request',['../client_cli.html#autotoc_md121',1,'2. Send an Untune Request'],['../index.html#autotoc_md112',1,'2. Send an Untune Request']]],
  ['and_20features_16',['1. Making Use of Relay Signals and Features',['../ext_features.html#autotoc_md129',1,'']]],
  ['and_20signal_20opcode_20sigcode_17',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md149',1,'']]],
  ['and_20subsequent_20cleanup_18',['4. Pulse Monitor: Detection of Dead Clients and Subsequent Cleanup',['../index.html#autotoc_md100',1,'']]],
  ['and_20teardown_20callbacks_19',['2. Applier and Teardown Callbacks',['../extensions_usage.html#autotoc_md126',1,'']]],
  ['and_20teardown_20capabilities_20',['2. Defining feature init, relay and teardown capabilities',['../ext_features.html#autotoc_md131',1,'']]],
  ['and_20untune_20functionalities_21',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md139',1,'']]],
  ['apis_22',['apis',['../index.html#autotoc_md21',1,'APIs'],['../group__RESOURCE__TUNER__CLIENT__APIS.html',1,'Client APIs'],['../index.html#autotoc_md76',1,'Example Usage of Resource Tuner APIs'],['../index.html#autotoc_md82',1,'Extension APIs']]],
  ['applier_20and_20teardown_20callbacks_23',['2. Applier and Teardown Callbacks',['../extensions_usage.html#autotoc_md126',1,'']]],
  ['architecture_20details_24',['4. How to enforce CPU architecture details',['../usage.html#autotoc_md144',1,'']]],
  ['aware_20operational_20modes_25',['8. Display-Aware Operational Modes',['../index.html#autotoc_md104',1,'']]]
];
