var searchData=
[
  ['rate_20limiter_0',['Rate Limiter',['../group__RATE__LIMITER.html',1,'']]],
  ['rate_20limiter_3a_20preventing_20system_20abuse_1',['5. Rate Limiter: Preventing System Abuse',['../index.html#autotoc_md101',1,'']]],
  ['ratelimiter_2',['RateLimiter',['../classRateLimiter.html',1,'']]],
  ['ratelimiter_2eh_3',['RateLimiter.h',['../RateLimiter_8h.html',1,'']]],
  ['readtargetinfo_4',['readTargetInfo',['../classTargetRegistry.html#a3f2d96aefc2104ff5761602b20f5a8a4',1,'TargetRegistry']]],
  ['recovery_5',['9. Crash Recovery',['../index.html#autotoc_md105',1,'']]],
  ['registerresource_6',['registerResource',['../classResourceRegistry.html#a080bc922577ebcb3bcac76b41dfa2a43',1,'ResourceRegistry']]],
  ['registersignal_7',['registerSignal',['../classSignalRegistry.html#ae43082c5f560725e6d505314b25e7e09',1,'SignalRegistry']]],
  ['relay_20and_20teardown_20capabilities_8',['2. Defining feature init, relay and teardown capabilities',['../ext_features.html#autotoc_md131',1,'']]],
  ['relay_20signals_20and_20features_9',['1. Making Use of Relay Signals and Features',['../ext_features.html#autotoc_md129',1,'']]],
  ['relaysignal_10',['relaysignal',['../index.html#autotoc_md32',1,'relaySignal'],['../group__RESOURCE__TUNER__CLIENT__APIS.html#ga5a4249a35267efc5c291069ca1a028e1',1,'relaySignal():&#160;UrmAPIs.h']]],
  ['relaytofeature_11',['relayToFeature',['../classExtFeaturesRegistry.html#a4e4331eae9f156bcc983eda62f4bfe74',1,'ExtFeaturesRegistry']]],
  ['removerequest_12',['removerequest',['../classRequestManager.html#ab9dd675017b66476e2dfa7ce4389023f',1,'RequestManager::removeRequest()'],['../classCocoTable.html#a74d26e26627f9b1fff71222543b3b97a',1,'CocoTable::removeRequest()']]],
  ['request_13',['request',['../index.html#autotoc_md111',1,'1. Send a Tune Request'],['../client_cli.html#autotoc_md120',1,'1. Send a Tune Request'],['../index.html#autotoc_md112',1,'2. Send an Untune Request'],['../client_cli.html#autotoc_md121',1,'2. Send an Untune Request'],['../client_cli.html#autotoc_md122',1,'3. Send a Retune Request'],['../index.html#autotoc_md113',1,'3. Send a Retune Request'],['../index.html#autotoc_md114',1,'4. Send a getProp Request'],['../client_cli.html#autotoc_md123',1,'4. Send a getProp Request'],['../index.html#autotoc_md115',1,'5. Send a tuneSignal Request'],['../client_cli.html#autotoc_md124',1,'5. Send a tuneSignal Request'],['../classRequest.html',1,'Request']]],
  ['request_20level_20priorities_14',['3. Request-Level Priorities',['../index.html#autotoc_md99',1,'']]],
  ['request_20processing_15',['Request Processing',['../index.html#autotoc_md95',1,'']]],
  ['requestmanager_16',['RequestManager',['../classRequestManager.html',1,'']]],
  ['requestqueue_17',['RequestQueue',['../classRequestQueue.html',1,'']]],
  ['requestreceiver_18',['RequestReceiver',['../classRequestReceiver.html',1,'']]],
  ['requests_20formulation_20guide_19',['&quot;Tune&quot; Requests Formulation Guide',['../requests_formulation.html',1,'']]],
  ['requesttype_20',['RequestType',['../Utils_8h.html#aae642cee2f4be03d228c36c0ccf8faef',1,'Utils.h']]],
  ['required_20modules_21',['Flexible Packaging: Packaging required modules',['../index.html#autotoc_md6',1,'']]],
  ['rescode_22',['Notes on Resource ResCode',['../index.html#autotoc_md73',1,'']]],
  ['rescode_20and_20signal_20opcode_20sigcode_23',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md149',1,'']]],
  ['resconfinfo_24',['ResConfInfo',['../structResConfInfo.html',1,'']]],
  ['resource_25',['resource',['../usage.html#autotoc_md135',1,'1. How to add a custom resource'],['../classResource.html',1,'Resource']]],
  ['resource_20config_20file_20with_20two_20resources_26',['Sample Resource config file with two resources.',['../usage.html#autotoc_md136',1,'']]],
  ['resource_20configs_27',['resource configs',['../index.html#autotoc_md49',1,'2. Resource Configs'],['../index.html#autotoc_md50',1,'Common Resource Configs'],['../index.html#autotoc_md51',1,'Overriding Resource Configs']]],
  ['resource_20format_28',['Resource Format',['../index.html#autotoc_md72',1,'']]],
  ['resource_20indexing_29',['Notes on Resource Indexing',['../usage.html#autotoc_md137',1,'']]],
  ['resource_20level_20policies_30',['2. Resource-Level Policies',['../index.html#autotoc_md98',1,'']]],
  ['resource_20manager_20key_20points_31',['Userspace Resource Manager Key Points',['../index.html#autotoc_md10',1,'']]],
  ['resource_20manager_3a_20a_20system_20resource_20tuning_20framework_32',['Userspace Resource Manager: A System Resource Tuning Framework',['../index.html',1,'']]],
  ['resource_20opcode_20rescode_20and_20signal_20opcode_20sigcode_33',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md149',1,'']]],
  ['resource_20rescode_34',['Notes on Resource ResCode',['../index.html#autotoc_md73',1,'']]],
  ['resource_20tune_20and_20untune_20functionalities_35',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md139',1,'']]],
  ['resource_20tuner_36',['Resource Tuner',['../index.html#autotoc_md11',1,'']]],
  ['resource_20tuner_20apis_37',['Example Usage of Resource Tuner APIs',['../index.html#autotoc_md76',1,'']]],
  ['resource_20tuner_20features_38',['Resource Tuner Features',['../index.html#autotoc_md93',1,'']]],
  ['resource_20types_20use_20this_20table_20to_20get_20the_20value_20of_20restype_20for_20a_20resource_39',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md74',1,'']]],
  ['resourceapplytype_40',['ResourceApplyType',['../structResourceApplyType.html',1,'']]],
  ['resourceregistry_41',['ResourceRegistry',['../classResourceRegistry.html',1,'']]],
  ['resources_42',['resources',['../index.html#autotoc_md19',1,'Resources'],['../usage.html#autotoc_md136',1,'Sample Resource config file with two resources.']]],
  ['restune_5fregister_5fapplier_5fcb_43',['RESTUNE_REGISTER_APPLIER_CB',['../index.html#autotoc_md83',1,'']]],
  ['restune_5fregister_5fconfig_44',['RESTUNE_REGISTER_CONFIG',['../index.html#autotoc_md89',1,'']]],
  ['restune_5fregister_5ftear_5fcb_45',['RESTUNE_REGISTER_TEAR_CB',['../index.html#autotoc_md86',1,'']]],
  ['restuneinternal_2eh_46',['RestuneInternal.h',['../RestuneInternal_8h.html',1,'']]],
  ['restuneparser_47',['RestuneParser',['../classRestuneParser.html',1,'']]],
  ['restype_20for_20a_20resource_48',['List Of Resource Types (Use this table to get the value of ResType for a Resource)',['../index.html#autotoc_md74',1,'']]],
  ['retune_20request_49',['retune request',['../client_cli.html#autotoc_md122',1,'3. Send a Retune Request'],['../index.html#autotoc_md113',1,'3. Send a Retune Request']]],
  ['retuneresources_50',['retuneresources',['../group__RESOURCE__TUNER__CLIENT__APIS.html#ga3e60de0521a903c940e47f2c0a1ced5a',1,'retuneResources():&#160;UrmAPIs.h'],['../index.html#autotoc_md24',1,'retuneResources'],['../index.html#autotoc_md78',1,'retuneResources']]]
];
